# permissions for end users to view skydives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skydive-viewer-role
rules:
- apiGroups:
  - config.skydive.network
  resources:
  - skydives
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.skydive.network
  resources:
  - skydives/status
  verbs:
  - get
